### ISSUE TITLE
Uncaught TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by BuZZ-dEE** [1000ch/atom-svgo#1]
**Atom Version**: 1.5.4
**System**: linux 4.4.1-2-ARCH
**Thrown From**: [svgo](https://github.com/1000ch/atom-svgo) package, v1.0.3

### Stack Trace

Uncaught TypeError: Cannot read property 'filter' of undefined

```
At /home/buzz-dee/.atom/packages/svgo/node_modules/svgo/lib/svgo/plugins.js:46

TypeError: Cannot read property 'filter' of undefined
    at monkeys (/home/buzz-dee/.atom/packages/svgo/node_modules/svgo/lib/svgo/plugins.js:46:38)
    at perItem (/home/buzz-dee/.atom/packages/svgo/node_modules/svgo/lib/svgo/plugins.js:77:12)
    at /home/buzz-dee/.atom/packages/svgo/node_modules/svgo/lib/svgo/plugins.js:18:24
    at Array.forEach (native)
    at module.exports (/home/buzz-dee/.atom/packages/svgo/node_modules/svgo/lib/svgo/plugins.js:14:13)
    at /home/buzz-dee/.atom/packages/svgo/node_modules/svgo/lib/svgo.js:63:17
    at Object.sax.onend (/home/buzz-dee/.atom/packages/svgo/node_modules/svgo/lib/svgo/svg2js.js:140:26)
    at emit (/home/buzz-dee/.atom/packages/svgo/node_modules/svgo/node_modules/sax/lib/sax.js:639:35)
    at end (/home/buzz-dee/.atom/packages/svgo/node_modules/svgo/node_modules/sax/lib/sax.js:682:5)
    at Object.write (/home/buzz-dee/.atom/packages/svgo/node_modules/svgo/node_modules/sax/lib/sax.js:989:14)
    at Object.SAXParser.close (/home/buzz-dee/.atom/packages/svgo/node_modules/svgo/node_modules/sax/lib/sax.js:156:38)
    at module.exports (/home/buzz-dee/.atom/packages/svgo/node_modules/svgo/lib/svgo/svg2js.js:144:21)
    at [object Object].SVGO._optimizeOnce (/home/buzz-dee/.atom/packages/svgo/node_modules/svgo/lib/svgo.js:56:5)
    at [object Object].SVGO.optimize (/home/buzz-dee/.atom/packages/svgo/node_modules/svgo/lib/svgo.js:48:11)
    at minify (/home/buzz-dee/.atom/packages/svgo/index.js:27:10)
    at atom-workspace.<anonymous> (/home/buzz-dee/.atom/packages/svgo/index.js:37:60)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:09.4.0 application:new-file (atom-text-editor.editor.is-focused)
  2x -0:08.2.0 svgo:minify (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.25
atom-ternjs, v0.13.2
autocomplete-python, v1.7.0
color-picker, v2.1.1
emmet, v2.4.1
highlight-selected, v0.11.2
language-fish-shell, v1.0.3
language-svg, v0.9.2
minimap, v4.19.0
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
pigments, v0.24.2
project-manager, v2.7.6
python-debugger, v0.0.2
python-indent, v0.4.1
python-isort, v0.0.7
python-tools, v0.6.7
svg-preview, v0.7.4
svgo, v1.0.3
term3, v0.21.2

# Dev
No dev packages
```

**Comment by BuZZ-dEE** [comment]
Why Ctrl + O used as shortcut? Ctrl + O already used for opening a file.

**Comment by 1000ch** [comment]
>Why Ctrl + O used as shortcut? Ctrl + O already used for opening a file.

Ah, that's my terrible mistake.

**Comment by 1000ch** [comment]
Changed to:

```cson
'atom-workspace':
  'ctrl-shift-o': 'svgo:minify'
  'ctrl-option-o': 'svgo:prettify'
```

Still occurring same error?

**Comment by 1000ch** [comment]
Update `atom-csso` to `v2.0.0` and issue again if same error occurred.
